### ISSUE TITLE
Configure external dependecies with package manager

### ISSUE THREAD

**Issue by hermonochy** [ShoweryCellar34/Ghoul-Engine#2]
Currently, external dependencies for submodule `Pentagram` are included as submodules   `glad`,  `glm`, `imgui`, `SDL` and   `stb`.
This is impractical to set up, hard to manage, error prone and wasteful.

Suggested action;

Use `conan` package manager to include these dependecies, and adapt `CMakeLists.txt`  files: Use `find_package` instead of `add_subdirectory`.
See https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html#

**Comment by ShoweryCellar34** [comment]
This is not a design choice i want
